<?php

return [
    'items' => [
        [
            'name' => 'home',
            'label' => 'Inicio',
            'path' => '/',
            'icon' => 'home',
            // Sin permiso: visible para todos los autenticados. La ruta real es / o /inicio (ver sidebar).
        ],
        [
            'name' => 'tareas',
            'label' => 'Tareas',
            'path' => '/tareas',
            'icon' => 'clipboard-list',
            'permiso' => 'tareas.ver',
        ],
        [
            'name' => 'clientes',
            'label' => 'Clientes',
            'icon' => 'users',
            'permiso' => 'clientes.ver',
            'submenu' => [
                ['name' => 'lista-clientes', 'label' => 'Lista clientes', 'path' => '/clientes', 'permiso' => 'clientes.ver'],
                //['name' => 'importar-csv', 'label' => 'Importar CSV', 'path' => '/clientes/importar-csv', 'permiso' => 'clientes.crear'],
                ['name' => 'lista-pedidos', 'label' => 'Lista pedidos', 'path' => '/pedidos', 'permiso' => 'pedidos.ver'],
                ['name' => 'agenda', 'label' => 'Agenda', 'path' => '/agenda', 'permiso' => 'agenda.ver'],
                ['name' => 'mapas-pedidos', 'label' => 'Mapas de pedidos', 'path' => '/clientes/mapas-pedidos', 'permiso' => 'pedidos.ver'],
            ],
        ],
        [
            'name' => 'servicios',
            'label' => 'Servicios',
            'icon' => 'wifi',
            'permiso' => 'servicios.ver',
            'submenu' => [
                ['name' => 'lista-servicios', 'label' => 'Lista servicios', 'path' => '/servicios', 'permiso' => 'servicios.ver'],
                ['name' => 'hotspot-dashboard', 'label' => 'Hotspot - Clientes activos', 'path' => '/hotspot/dashboard', 'permiso' => 'servicios.ver'],
                ['name' => 'hotspot-usuarios', 'label' => 'Usuarios Hotspot', 'path' => '/hotspot', 'permiso' => 'servicios.ver'],
                ['name' => 'hotspot-perfiles', 'label' => 'Perfiles Hotspot', 'path' => '/hotspot/perfiles', 'permiso' => 'servicios.ver'],
            ],
        ],
        [
            'name' => 'tv-streaming',
            'label' => 'TV streaming',
            'path' => '/tv-cuentas',
            'icon' => 'tv',
            'permiso' => 'tv.ver',
        ],
        [
            'name' => 'inventario',
            'label' => 'Inventario',
            'icon' => 'cube',
            'permiso' => 'inventario.ver',
            'submenu' => [
                ['name' => 'productos', 'label' => 'Productos / Equipos', 'path' => '/productos', 'permiso' => 'inventario.ver'],
                ['name' => 'compras', 'label' => 'Compras', 'path' => '/compras', 'permiso' => 'inventario.ver'],
                ['name' => 'ventas', 'label' => 'Ventas', 'path' => '/ventas', 'permiso' => 'inventario.ver'],
                ['name' => 'gastos', 'label' => 'Gastos', 'path' => '/gastos', 'permiso' => 'inventario.ver'],
                ['name' => 'proveedores', 'label' => 'Proveedores', 'path' => '/proveedores', 'permiso' => 'inventario.ver'],
                ['name' => 'categorias-producto', 'label' => 'Categorías producto', 'path' => '/categorias-producto', 'permiso' => 'inventario.ver'],
                ['name' => 'categorias-gasto', 'label' => 'Categorías gasto', 'path' => '/categorias-gasto', 'permiso' => 'inventario.ver'],
            ],
        ],
        [
            'name' => 'facturacion',
            'label' => 'Facturación',
            'icon' => 'currency',
            'permiso' => 'facturacion.ver',
            'submenu' => [
                ['name' => 'facturas', 'label' => 'Facturas electrónicas', 'path' => '/facturas', 'permiso' => 'facturas.ver'],
                ['name' => 'factura-internas', 'label' => 'Facturas internas', 'path' => '/factura-internas', 'permiso' => 'factura-interna.ver'],
                ['name' => 'pendiente-pago', 'label' => 'Pendiente de pago', 'path' => '/factura-internas/pendientes', 'permiso' => 'pagos-pendientes.ver'],
                ['name' => 'cobros-servicios', 'label' => 'Cobros', 'path' => '/cobros/servicios', 'permiso' => 'cobros.ver'],
                ['name' => 'cobros', 'label' => 'Cobros y recibos', 'path' => '/cobros', 'permiso' => 'cobros.ver'],
            ],
        ],
        [
            'name' => 'tickets',
            'label' => 'Tickets',
            'path' => '/tickets',
            'icon' => 'ticket',
            'permiso' => 'tickets.ver',
        ],
        [
            'name' => 'usuarios',
            'label' => 'Usuarios',
            'path' => '/usuarios',
            'icon' => 'user-group',
            'permiso' => 'usuarios.ver',
        ],
        [
            'name' => 'configuracion',
            'label' => 'Configuración',
            'path' => '/configuracion',
            'icon' => 'cog',
            'permiso' => 'configuracion.ver',
            'submenu' => [
                ['name' => 'config-impresion', 'label' => 'Impresión', 'path' => '/configuracion/impresion', 'permiso' => 'configuracion.ver'],
                ['name' => 'config-ajustes', 'label' => 'Ajustes generales', 'path' => '/configuracion/ajustes', 'permiso' => 'configuracion.ver'],
                ['name' => 'config-facturacion', 'label' => 'Facturación y servicios', 'path' => '/configuracion/facturacion', 'permiso' => 'configuracion.ver'],
                ['name' => 'config-tareas-periodicas', 'label' => 'Tareas periódicas', 'path' => '/configuracion/tareas-periodicas', 'permiso' => 'configuracion.ver'],
            ],
        ],
        [
            'name' => 'ftth',
            'label' => 'FTTH',
            'icon' => 'server',
            'permiso' => 'sistema.ver',
            'submenu' => [
                ['name' => 'olts', 'label' => 'OLTs', 'path' => '/sistema/olts', 'permiso' => 'sistema.ver'],
                ['name' => 'olt-marcas', 'label' => 'Marcas OLT', 'path' => '/sistema/olt-marcas', 'permiso' => 'sistema.ver'],
                ['name' => 'cajas-nap', 'label' => 'Cajas NAP', 'path' => '/sistema/cajas-nap', 'permiso' => 'sistema.ver'],
                ['name' => 'cajas-nap-mapa', 'label' => 'Mapa infraestructura óptica', 'path' => '/sistema/cajas-nap/mapa', 'permiso' => 'sistema.ver'],
                ['name' => 'salida-pons', 'label' => 'Salidas PON', 'path' => '/sistema/salida-pons', 'permiso' => 'sistema.ver'],
                ['name' => 'lineas-cable', 'label' => 'Líneas de cable', 'path' => '/sistema/lineas-cable', 'permiso' => 'sistema.ver'],
            ],
        ],
        [
            'name' => 'sistema',
            'label' => 'Sistema',
            'icon' => 'server',
            'permiso' => 'sistema.ver',
            'submenu' => [
                ['name' => 'auditoria', 'label' => 'Auditoría', 'path' => '/sistema/auditoria', 'permiso' => 'sistema.ver'],
                ['name' => 'routers', 'label' => 'Routers', 'path' => '/sistema/routers', 'permiso' => 'sistema.ver'],
                ['name' => 'router-ip-pools', 'label' => 'Pools de IP', 'path' => '/sistema/router-ip-pools', 'permiso' => 'sistema.ver'],
                ['name' => 'importar-wisphub', 'label' => 'Importar WispHub', 'path' => '/sistema/importar-wisphub', 'permiso' => 'sistema.ver'],
            ],
        ],
        [
            'name' => 'referenciales',
            'label' => 'Referenciales',
            'icon' => 'document',
            'permiso' => 'referenciales.ver',
            'submenu' => [
                ['name' => 'estados-pedidos', 'label' => 'Estados de pedidos', 'path' => '/estados-pedidos', 'permiso' => 'referenciales.ver'],
                ['name' => 'planes', 'label' => 'Planes', 'path' => '/planes', 'permiso' => 'planes.ver'],
                ['name' => 'tipos-tecnologias', 'label' => 'Tipos de tecnologías', 'path' => '/tipos-tecnologias', 'permiso' => 'referenciales.ver'],
                ['name' => 'perfiles-pppoe', 'label' => 'Perfiles PPPoE', 'path' => '/perfiles-pppoe', 'permiso' => 'referenciales.ver'],
                ['name' => 'nodos', 'label' => 'Nodos', 'path' => '/nodos', 'permiso' => 'referenciales.ver'],
                ['name' => 'roles', 'label' => 'Roles', 'path' => '/roles', 'permiso' => 'referenciales.ver'],
            ],
        ],
        [
            'name' => 'mas',
            'label' => 'Más',
            'icon' => 'document',
            'submenu' => [
                ['name' => 'ayuda', 'label' => 'Ayuda', 'path' => '/ayuda'],
                ['name' => 'reportes', 'label' => 'Reportes', 'path' => '/reportes'],
            ],
        ],
    ],
];
