<?php

return [
    'items' => [
        [
            'name' => 'home',
            'label' => 'Inicio',
            'path' => '/',
            'icon' => 'home',
            'permiso' => 'inicio.ver',
        ],
        [
            'name' => 'corte-servicio',
            'label' => 'Corte de servicio',
            'path' => '/admin/corte-servicio',
            'icon' => 'bolt',
            'admin_only' => true,
        ],
        [
            'name' => 'mapa-tecnicos',
            'label' => 'Técnicos en mapa',
            'path' => '/staff/mapa-tecnicos',
            'icon' => 'map',
            'permiso' => 'staff-mapa-tecnicos.ver',
        ],
        [
            'name' => 'tareas',
            'label' => 'Tareas',
            'path' => '/tareas',
            'icon' => 'clipboard-list',
            'permiso' => 'tareas.ver',
        ],
        [
            'name' => 'clientes',
            'label' => 'Clientes',
            'icon' => 'users',
            'submenu' => [
                ['name' => 'clientes-dashboard', 'label' => 'Dashboard', 'path' => '/clientes/dashboard', 'permiso' => 'clientes-dashboard.ver'],
                ['name' => 'lista-clientes', 'label' => 'Lista clientes', 'path' => '/clientes', 'permiso' => 'clientes-lista.ver'],
                ['name' => 'solicitudes-acceso', 'label' => 'Solicitudes app', 'path' => '/solicitudes-acceso', 'permiso' => 'solicitudes-acceso.ver'],
                ['name' => 'avisos-push', 'label' => 'Avisos push', 'path' => '/avisos-push', 'permiso' => 'avisos-push.ver'],
                ['name' => 'lista-pedidos', 'label' => 'Lista pedidos', 'path' => '/pedidos', 'permiso' => 'clientes-pedidos.ver'],
                ['name' => 'agenda', 'label' => 'Agenda', 'path' => '/agenda', 'permiso' => 'clientes-agenda.ver'],
                ['name' => 'mapas-pedidos', 'label' => 'Mapas de pedidos', 'path' => '/clientes/mapas-pedidos', 'permiso' => 'clientes-mapa-pedidos.ver'],
            ],
        ],
        [
            'name' => 'whatsapp',
            'label' => 'WhatsApp',
            'path' => '/whatsapp/mensajes',
            'icon' => 'chat',
            'permiso' => 'whatsapp.ver',
            'activePrefix' => '/whatsapp',
        ],
        [
            'name' => 'servicios',
            'label' => 'Servicios',
            'icon' => 'wifi',
            'submenu' => [
                ['name' => 'lista-servicios', 'label' => 'Lista servicios', 'path' => '/servicios', 'permiso' => 'servicios-lista.ver'],
                ['name' => 'pppoe-eventos', 'label' => 'Eventos PPPoE MikroTik', 'path' => '/servicios/pppoe-eventos', 'permiso' => 'servicios-lista.ver'],
                ['name' => 'hotspot-dashboard', 'label' => 'Hotspot - Clientes activos', 'path' => '/hotspot/dashboard', 'permiso' => 'servicios-hotspot.ver'],
                ['name' => 'hotspot-usuarios', 'label' => 'Usuarios Hotspot', 'path' => '/hotspot', 'permiso' => 'servicios-hotspot-usuarios.ver'],
                ['name' => 'hotspot-perfiles', 'label' => 'Perfiles Hotspot', 'path' => '/hotspot/perfiles', 'permiso' => 'servicios-hotspot-perfiles.ver'],
            ],
        ],
        [
            'name' => 'tv-streaming',
            'label' => 'TV streaming',
            'path' => '/tv-cuentas',
            'icon' => 'tv',
            'permiso' => 'tv.ver',
        ],
        [
            'name' => 'inventario',
            'label' => 'Inventario',
            'icon' => 'cube',
            'submenu' => [
                ['name' => 'productos', 'label' => 'Productos / Equipos', 'path' => '/productos', 'permiso' => 'inventario-productos.ver'],
                ['name' => 'compras', 'label' => 'Compras', 'path' => '/compras', 'permiso' => 'inventario-compras.ver'],
                ['name' => 'ventas', 'label' => 'Ventas', 'path' => '/ventas', 'permiso' => 'inventario-ventas.ver'],
                ['name' => 'gastos', 'label' => 'Gastos', 'path' => '/gastos', 'permiso' => 'inventario-gastos.ver'],
                ['name' => 'proveedores', 'label' => 'Proveedores', 'path' => '/proveedores', 'permiso' => 'inventario-proveedores.ver'],
                ['name' => 'categorias-producto', 'label' => 'Categorías producto', 'path' => '/categorias-producto', 'permiso' => 'inventario-categorias-producto.ver'],
                ['name' => 'categorias-gasto', 'label' => 'Categorías gasto', 'path' => '/categorias-gasto', 'permiso' => 'inventario-categorias-gasto.ver'],
            ],
        ],
        [
            'name' => 'facturacion',
            'label' => 'Facturación',
            'icon' => 'currency',
            'submenu' => [
                ['name' => 'facturacion-dashboard', 'label' => 'Dashboard', 'path' => '/facturacion/dashboard', 'permiso' => 'facturacion-dashboard.ver', 'admin_only' => true],
                ['name' => 'facturas', 'label' => 'Facturas electrónicas', 'path' => '/facturas', 'permiso' => 'facturas.ver'],
                ['name' => 'factura-internas', 'label' => 'Facturas internas', 'path' => '/factura-internas', 'permiso' => 'factura-interna.ver'],
                ['name' => 'notas-credito-internas', 'label' => 'Notas de crédito', 'path' => '/factura-internas/notas-credito', 'permiso' => 'notas-credito.ver'],
                ['name' => 'pendiente-pago', 'label' => 'Pendiente de pago', 'path' => '/factura-internas/pendientes', 'permiso' => 'pagos-pendientes.ver'],
                ['name' => 'promesas-pago', 'label' => 'Promesas de pago', 'path' => '/promesas-pago', 'permiso' => 'promesas-pago.ver'],
                ['name' => 'cobros-servicios', 'label' => 'Cobros', 'path' => '/cobros/servicios', 'permiso' => 'cobros-servicios.ver'],
                ['name' => 'cobros', 'label' => 'Cobros y recibos', 'path' => '/cobros', 'permiso' => 'cobros.ver'],
                ['name' => 'cobros-rendicion', 'label' => 'Rendición de efectivo', 'path' => '/cobros/rendiciones', 'permiso' => 'cobros-rendicion.ver'],
            ],
        ],
        [
            'name' => 'tickets',
            'label' => 'Tickets',
            'path' => '/tickets',
            'icon' => 'ticket',
            'permiso' => 'tickets.ver',
        ],
        [
            'name' => 'usuarios',
            'label' => 'Usuarios',
            'icon' => 'user-group',
            'permiso' => 'usuarios.ver',
            'submenu' => [
                ['name' => 'usuarios-lista', 'label' => 'Personal y clientes', 'path' => '/usuarios', 'permiso' => 'usuarios.ver'],
                ['name' => 'usuarios-sesiones', 'label' => 'Sesiones activas', 'path' => '/usuarios/sesiones', 'permiso' => 'usuarios.ver'],
            ],
        ],
        [
            'name' => 'configuracion',
            'label' => 'Configuración',
            'path' => '/configuracion',
            'icon' => 'cog',
            'submenu' => [
                ['name' => 'config-impresion', 'label' => 'Impresión', 'path' => '/configuracion/impresion'],
                ['name' => 'config-ajustes', 'label' => 'Ajustes generales', 'path' => '/configuracion/ajustes', 'permiso' => 'configuracion-ajustes.ver'],
                ['name' => 'config-facturacion', 'label' => 'Facturación y servicios', 'path' => '/configuracion/facturacion', 'permiso' => 'configuracion-facturacion.ver'],
                ['name' => 'config-sifen', 'label' => 'SIFEN e-Kuatia', 'path' => '/configuracion/sifen', 'permiso' => 'configuracion-sifen.ver'],
                ['name' => 'config-sifen-prueba', 'label' => 'Prueba SIFEN', 'path' => '/configuracion/sifen/prueba', 'permiso' => 'configuracion-sifen.ver'],
                ['name' => 'config-tareas-periodicas', 'label' => 'Tareas periódicas', 'path' => '/configuracion/tareas-periodicas', 'permiso' => 'configuracion-tareas-periodicas.ver'],
                ['name' => 'config-backup-bd', 'label' => 'Backup base de datos', 'path' => '/configuracion/backup-bd', 'permiso' => 'configuracion-backup.ver'],
            ],
        ],
        [
            'name' => 'ftth',
            'label' => 'FTTH',
            'icon' => 'server',
            'submenu' => [
                ['name' => 'olts', 'label' => 'OLTs', 'path' => '/sistema/olts', 'permiso' => 'ftth-olts.ver'],
                ['name' => 'olt-modelos', 'label' => 'Catálogo OLT', 'path' => '/sistema/olt-modelos', 'permiso' => 'ftth-olts.ver'],
                ['name' => 'olt-marcas', 'label' => 'Marcas OLT', 'path' => '/sistema/olt-marcas', 'permiso' => 'ftth-marcas-olt.ver'],
                ['name' => 'cajas-nap', 'label' => 'Cajas NAP', 'path' => '/sistema/cajas-nap', 'permiso' => 'ftth-cajas-nap.ver'],
                ['name' => 'cajas-nap-mapa', 'label' => 'Mapa infraestructura óptica', 'path' => '/sistema/cajas-nap/mapa', 'permiso' => 'ftth-mapa-optico.ver'],
                ['name' => 'salida-pons', 'label' => 'Salidas PON', 'path' => '/sistema/salida-pons', 'permiso' => 'ftth-salidas-pon.ver'],
                ['name' => 'lineas-cable', 'label' => 'Líneas de cable', 'path' => '/sistema/lineas-cable', 'permiso' => 'ftth-lineas-cable.ver'],
            ],
        ],
        [
            'name' => 'sistema',
            'label' => 'Sistema',
            'icon' => 'server',
            'submenu' => [
                ['name' => 'auditoria', 'label' => 'Auditoría', 'path' => '/sistema/auditoria', 'permiso' => 'sistema-routers.ver'],
                ['name' => 'routers', 'label' => 'Routers', 'path' => '/sistema/routers', 'permiso' => 'sistema-routers.ver'],
                ['name' => 'router-modelos', 'label' => 'Catálogo MikroTik', 'path' => '/sistema/router-modelos', 'permiso' => 'sistema-routers.ver'],
                ['name' => 'router-ip-pools', 'label' => 'Pools de IP', 'path' => '/sistema/router-ip-pools', 'permiso' => 'sistema-pools-ip.ver'],
                ['name' => 'importar-wisphub', 'label' => 'Importar WispHub', 'path' => '/sistema/importar-wisphub', 'permiso' => 'sistema-routers.ver'],
                ['name' => 'mikrotik-pendientes', 'label' => 'MikroTik pendientes', 'path' => '/sistema/mikrotik-pendientes', 'permiso' => 'sistema-mikrotik-pendientes.ver'],
            ],
        ],
        [
            'name' => 'loyalty',
            'label' => 'Loyalty / App',
            'icon' => 'document',
            'permiso_any' => [
                'loyalty-novedades.ver',
                'loyalty-premios.ver',
                'loyalty-canjes.ver',
                'loyalty-puntos.ver',
                'loyalty-upsell.ver',
                'loyalty-app-config.ver',
            ],
            'submenu' => [
                [
                    'name' => 'loyalty-dashboard',
                    'label' => 'Dashboard',
                    'path' => '/loyalty',
                    'permiso_any' => [
                        'loyalty-novedades.ver',
                        'loyalty-premios.ver',
                        'loyalty-canjes.ver',
                        'loyalty-puntos.ver',
                        'loyalty-upsell.ver',
                        'loyalty-app-config.ver',
                    ],
                ],
                ['name' => 'loyalty-novedades', 'label' => 'Novedades', 'path' => '/loyalty/novedades', 'permiso' => 'loyalty-novedades.ver'],
                ['name' => 'loyalty-premios', 'label' => 'Premios', 'path' => '/loyalty/premios', 'permiso' => 'loyalty-premios.ver'],
                ['name' => 'loyalty-canjes', 'label' => 'Cola de canjes', 'path' => '/loyalty/canjes', 'permiso' => 'loyalty-canjes.ver'],
                ['name' => 'loyalty-puntos', 'label' => 'Puntos y reglas', 'path' => '/loyalty/puntos', 'permiso' => 'loyalty-puntos.ver'],
                ['name' => 'loyalty-upsell', 'label' => 'Planes upsell', 'path' => '/loyalty/upsell', 'permiso' => 'loyalty-upsell.ver'],
                ['name' => 'loyalty-app-config', 'label' => 'App clientes', 'path' => '/loyalty/app-config', 'permiso' => 'loyalty-app-config.ver'],
            ],
        ],
        [
            'name' => 'referenciales',
            'label' => 'Referenciales',
            'icon' => 'document',
            'submenu' => [
                ['name' => 'estados-pedidos', 'label' => 'Estados de pedidos', 'path' => '/estados-pedidos', 'permiso' => 'clientes-pedidos.ver'],
                ['name' => 'planes', 'label' => 'Planes', 'path' => '/planes', 'permiso' => 'planes.ver'],
                ['name' => 'tipos-tecnologias', 'label' => 'Tipos de tecnologías', 'path' => '/tipos-tecnologias', 'permiso' => 'tipos-tecnologia.ver'],
                ['name' => 'perfiles-pppoe', 'label' => 'Perfiles PPPoE', 'path' => '/perfiles-pppoe', 'permiso' => 'perfiles-pppoe.ver'],
                ['name' => 'nodos', 'label' => 'Nodos', 'path' => '/nodos', 'permiso' => 'nodos.ver'],
                ['name' => 'roles', 'label' => 'Roles', 'path' => '/roles', 'permiso' => 'roles.ver'],
                ['name' => 'ticket-asuntos', 'label' => 'Asuntos de tickets', 'path' => '/ticket-asuntos', 'permiso' => 'ticket-asuntos.ver'],
            ],
        ],
        [
            'name' => 'mas',
            'label' => 'Más',
            'icon' => 'document',
            'submenu' => [
                ['name' => 'ayuda', 'label' => 'Ayuda', 'path' => '/ayuda'],
                ['name' => 'reportes', 'label' => 'Reportes', 'path' => '/reportes'],
            ],
        ],
    ],
];
