<?php

return [
    'items' => [
        [
            'name' => 'home',
            'label' => 'Inicio',
            'path' => '/',
            'icon' => 'home',
            'permiso' => 'inicio.ver',
        ],
        [
            'name' => 'corte-servicio',
            'label' => 'Corte de servicio',
            'path' => '/admin/corte-servicio',
            'icon' => 'bolt',
            'admin_only' => true,
        ],
        [
            'name' => 'tareas',
            'label' => 'Tareas',
            'path' => '/tareas',
            'icon' => 'clipboard-list',
            'permiso' => 'tareas.ver',
        ],
        [
            'name' => 'clientes',
            'label' => 'Clientes',
            'icon' => 'users',
            'submenu' => [
                ['name' => 'clientes-dashboard', 'label' => 'Dashboard', 'path' => '/clientes/dashboard', 'permiso' => 'clientes-dashboard.ver'],
                ['name' => 'lista-clientes', 'label' => 'Lista clientes', 'path' => '/clientes', 'permiso' => 'clientes-lista.ver'],
                ['name' => 'lista-pedidos', 'label' => 'Lista pedidos', 'path' => '/pedidos', 'permiso' => 'clientes-pedidos.ver'],
                ['name' => 'agenda', 'label' => 'Agenda', 'path' => '/agenda', 'permiso' => 'clientes-agenda.ver'],
                ['name' => 'mapas-pedidos', 'label' => 'Mapas de pedidos', 'path' => '/clientes/mapas-pedidos', 'permiso' => 'clientes-mapa-pedidos.ver'],
            ],
        ],
        [
            'name' => 'servicios',
            'label' => 'Servicios',
            'icon' => 'wifi',
            'submenu' => [
                ['name' => 'lista-servicios', 'label' => 'Lista servicios', 'path' => '/servicios', 'permiso' => 'servicios-lista.ver'],
                ['name' => 'hotspot-dashboard', 'label' => 'Hotspot - Clientes activos', 'path' => '/hotspot/dashboard', 'permiso' => 'servicios-hotspot.ver'],
                ['name' => 'hotspot-usuarios', 'label' => 'Usuarios Hotspot', 'path' => '/hotspot', 'permiso' => 'servicios-hotspot-usuarios.ver'],
                ['name' => 'hotspot-perfiles', 'label' => 'Perfiles Hotspot', 'path' => '/hotspot/perfiles', 'permiso' => 'servicios-hotspot-perfiles.ver'],
            ],
        ],
        [
            'name' => 'tv-streaming',
            'label' => 'TV streaming',
            'path' => '/tv-cuentas',
            'icon' => 'tv',
            'permiso' => 'tv.ver',
        ],
        [
            'name' => 'inventario',
            'label' => 'Inventario',
            'icon' => 'cube',
            'submenu' => [
                ['name' => 'productos', 'label' => 'Productos / Equipos', 'path' => '/productos', 'permiso' => 'inventario-productos.ver'],
                ['name' => 'compras', 'label' => 'Compras', 'path' => '/compras', 'permiso' => 'inventario-compras.ver'],
                ['name' => 'ventas', 'label' => 'Ventas', 'path' => '/ventas', 'permiso' => 'inventario-ventas.ver'],
                ['name' => 'gastos', 'label' => 'Gastos', 'path' => '/gastos', 'permiso' => 'inventario-gastos.ver'],
                ['name' => 'proveedores', 'label' => 'Proveedores', 'path' => '/proveedores', 'permiso' => 'inventario-proveedores.ver'],
                ['name' => 'categorias-producto', 'label' => 'Categorías producto', 'path' => '/categorias-producto', 'permiso' => 'inventario-categorias-producto.ver'],
                ['name' => 'categorias-gasto', 'label' => 'Categorías gasto', 'path' => '/categorias-gasto', 'permiso' => 'inventario-categorias-gasto.ver'],
            ],
        ],
        [
            'name' => 'facturacion',
            'label' => 'Facturación',
            'icon' => 'currency',
            'submenu' => [
                ['name' => 'facturacion-dashboard', 'label' => 'Dashboard', 'path' => '/facturacion/dashboard', 'permiso' => 'facturacion-dashboard.ver', 'admin_only' => true],
                ['name' => 'facturas', 'label' => 'Facturas electrónicas', 'path' => '/facturas', 'permiso' => 'facturas.ver'],
                ['name' => 'factura-internas', 'label' => 'Facturas internas', 'path' => '/factura-internas', 'permiso' => 'factura-interna.ver'],
                ['name' => 'notas-credito-internas', 'label' => 'Notas de crédito', 'path' => '/factura-internas/notas-credito', 'permiso' => 'notas-credito.ver'],
                ['name' => 'pendiente-pago', 'label' => 'Pendiente de pago', 'path' => '/factura-internas/pendientes', 'permiso' => 'pagos-pendientes.ver'],
                ['name' => 'promesas-pago', 'label' => 'Promesas de pago', 'path' => '/promesas-pago', 'permiso' => 'promesas-pago.ver'],
                ['name' => 'cobros-servicios', 'label' => 'Cobros', 'path' => '/cobros/servicios', 'permiso' => 'cobros-servicios.ver'],
                ['name' => 'cobros', 'label' => 'Cobros y recibos', 'path' => '/cobros', 'permiso' => 'cobros.ver'],
            ],
        ],
        [
            'name' => 'tickets',
            'label' => 'Tickets',
            'path' => '/tickets',
            'icon' => 'ticket',
            'permiso' => 'tickets.ver',
        ],
        [
            'name' => 'usuarios',
            'label' => 'Usuarios',
            'path' => '/usuarios',
            'icon' => 'user-group',
            'permiso' => 'usuarios.ver',
        ],
        [
            'name' => 'configuracion',
            'label' => 'Configuración',
            'path' => '/configuracion',
            'icon' => 'cog',
            'submenu' => [
                ['name' => 'config-impresion', 'label' => 'Impresión', 'path' => '/configuracion/impresion'],
                ['name' => 'config-ajustes', 'label' => 'Ajustes generales', 'path' => '/configuracion/ajustes', 'permiso' => 'configuracion-ajustes.ver'],
                ['name' => 'config-facturacion', 'label' => 'Facturación y servicios', 'path' => '/configuracion/facturacion', 'permiso' => 'configuracion-facturacion.ver'],
                ['name' => 'config-sifen', 'label' => 'SIFEN e-Kuatia', 'path' => '/configuracion/sifen', 'permiso' => 'configuracion-sifen.ver'],
                ['name' => 'config-tareas-periodicas', 'label' => 'Tareas periódicas', 'path' => '/configuracion/tareas-periodicas', 'permiso' => 'configuracion-tareas-periodicas.ver'],
                ['name' => 'config-backup-bd', 'label' => 'Backup base de datos', 'path' => '/configuracion/backup-bd', 'permiso' => 'configuracion-backup.ver'],
            ],
        ],
        [
            'name' => 'ftth',
            'label' => 'FTTH',
            'icon' => 'server',
            'submenu' => [
                ['name' => 'olts', 'label' => 'OLTs', 'path' => '/sistema/olts', 'permiso' => 'ftth-olts.ver'],
                ['name' => 'olt-marcas', 'label' => 'Marcas OLT', 'path' => '/sistema/olt-marcas', 'permiso' => 'ftth-marcas-olt.ver'],
                ['name' => 'cajas-nap', 'label' => 'Cajas NAP', 'path' => '/sistema/cajas-nap', 'permiso' => 'ftth-cajas-nap.ver'],
                ['name' => 'cajas-nap-mapa', 'label' => 'Mapa infraestructura óptica', 'path' => '/sistema/cajas-nap/mapa', 'permiso' => 'ftth-mapa-optico.ver'],
                ['name' => 'salida-pons', 'label' => 'Salidas PON', 'path' => '/sistema/salida-pons', 'permiso' => 'ftth-salidas-pon.ver'],
                ['name' => 'lineas-cable', 'label' => 'Líneas de cable', 'path' => '/sistema/lineas-cable', 'permiso' => 'ftth-lineas-cable.ver'],
            ],
        ],
        [
            'name' => 'sistema',
            'label' => 'Sistema',
            'icon' => 'server',
            'submenu' => [
                ['name' => 'auditoria', 'label' => 'Auditoría', 'path' => '/sistema/auditoria', 'permiso' => 'sistema-routers.ver'],
                ['name' => 'routers', 'label' => 'Routers', 'path' => '/sistema/routers', 'permiso' => 'sistema-routers.ver'],
                ['name' => 'router-ip-pools', 'label' => 'Pools de IP', 'path' => '/sistema/router-ip-pools', 'permiso' => 'sistema-pools-ip.ver'],
                ['name' => 'importar-wisphub', 'label' => 'Importar WispHub', 'path' => '/sistema/importar-wisphub', 'permiso' => 'sistema-routers.ver'],
                ['name' => 'mikrotik-pendientes', 'label' => 'MikroTik pendientes', 'path' => '/sistema/mikrotik-pendientes', 'permiso' => 'sistema-mikrotik-pendientes.ver'],
            ],
        ],
        [
            'name' => 'referenciales',
            'label' => 'Referenciales',
            'icon' => 'document',
            'submenu' => [
                ['name' => 'estados-pedidos', 'label' => 'Estados de pedidos', 'path' => '/estados-pedidos', 'permiso' => 'clientes-pedidos.ver'],
                ['name' => 'planes', 'label' => 'Planes', 'path' => '/planes', 'permiso' => 'planes.ver'],
                ['name' => 'tipos-tecnologias', 'label' => 'Tipos de tecnologías', 'path' => '/tipos-tecnologias', 'permiso' => 'tipos-tecnologia.ver'],
                ['name' => 'perfiles-pppoe', 'label' => 'Perfiles PPPoE', 'path' => '/perfiles-pppoe', 'permiso' => 'perfiles-pppoe.ver'],
                ['name' => 'nodos', 'label' => 'Nodos', 'path' => '/nodos', 'permiso' => 'nodos.ver'],
                ['name' => 'roles', 'label' => 'Roles', 'path' => '/roles', 'permiso' => 'roles.ver'],
                ['name' => 'ticket-asuntos', 'label' => 'Asuntos de tickets', 'path' => '/ticket-asuntos', 'permiso' => 'ticket-asuntos.ver'],
            ],
        ],
        [
            'name' => 'mas',
            'label' => 'Más',
            'icon' => 'document',
            'submenu' => [
                ['name' => 'ayuda', 'label' => 'Ayuda', 'path' => '/ayuda'],
                ['name' => 'reportes', 'label' => 'Reportes', 'path' => '/reportes'],
            ],
        ],
    ],
];
